name: "Run Tests"
description: "Run Unit Tests/Code Quality Checks/etc. on Front-End Code"

runs:
  using: "composite"
  steps:
    - name: Run Unit Tests
      run: |
        cd frontend
        npm test
      shell: bash
      env:
        CI: true
