name: React CI/CD AWS CDK
on:
  push:
    branches:
      - master
    paths:
      - "aws-cdk/static_site_stack/**"
      - "aws-cdk/certificate_stack/**"
      - "aws-cdk/app.py"
      - "frontend/src/**"
      - ".github/**" # Uncomment to test workflow changes

jobs:
  build:
    env:
      DOMAIN: ${{ secrets.AWS_DOMAIN_NAME }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.x"
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Dependencies
        run: |
          cd frontend
          npm install
      - name: Run Front-End Tests
        uses: ./.github/actions/run-tests
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Create and Deploy AWS Resources
        uses: ./.github/actions/create-stacks
      - name: Create Build & Deploy to S3 Bucket
        run: |
          cd frontend
          npm run build
          aws s3 sync ./build s3://$BUCKET --delete
      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
